name: pydsft
channels:
  - conda-forge
  - defaults
dependencies:
  - dnspython
  - imageio
  - ipython
  - ipywidgets
  - jupyterlab
  - jupyterlab_widgets
  - matplotlib
  - nltk
  - nodejs
  - numpy
  - pandas
  - pip
  - pymongo
  - python=3.10
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - sqlite
  - statsmodels
  - tensorflow
  - pip:
    - deepl
    - dweepy
    - folium
    - geopy
    - ibm-watson
    - mastodon
    - pubnub
    - pydub
    - textblob
    - tweepy
    - tweet-preprocessor
    - wordcloud
